name: "Deploy - On branch main/release Push"
on:
  push:
    branches:
      - main
      - 'releases/**'
    paths-ignore:
      - '.bumpversion.cfg'
      - 'setup.py'

jobs:
  CI:
    uses: MOV-AI/.github/.github/workflows/py-workflow.yml@v1
    with:
      deploy: 'true'
    secrets:
      auto_commit_user: ${{ secrets.RAISE_BOT_COMMIT_USER }}
      auto_commit_mail: ${{ secrets.RAISE_BOT_COMMIT_MAIL }}
      registry_user: ${{ secrets.PORTUS_APP_USER }}
      registry_password: ${{ secrets.PORTUS_APP_TOKEN }}
      nexus_publisher_user: ${{ secrets.NEXUS_PUBLISHER_USR }}
      nexus_publisher_password: ${{ secrets.NEXUS_PUBLISHER_PWD }}
      gh_token: ${{ secrets.GITHUB_TOKEN }}
      sonar_token: ${{ secrets.SONAR_TOKEN }}
      
  CI-docker-melodic:
    needs: [CI-pip]
    uses: MOV-AI/.github/.github/workflows/docker-workflow.yml@feat/docker_args
    with:
      docker_file: docker/melodic/Dockerfile
      docker_image: devops/backend-melodic
      github_ref: ${{ github.ref }}
      build_args: PIP_PACKAGE_REPO=https://artifacts.cloud.mov.ai/repository/pypi-integration/simple
      public: true
      public_image: ce/backend-melodic
      deploy: true
    secrets:
      registry_user: ${{ secrets.PORTUS_APP_USER }}
      registry_password: ${{ secrets.PORTUS_APP_TOKEN }}

  CI-docker-noetic:
    needs: [CI-pip]
    uses: MOV-AI/.github/.github/workflows/docker-workflow.yml@feat/docker_args
    with:
      docker_file: docker/noetic/Dockerfile
      docker_image: devops/backend-noetic
      github_ref: ${{ github.ref }}
      build_args: PIP_PACKAGE_REPO=https://artifacts.cloud.mov.ai/repository/pypi-integration/simple
      public: true
      public_image: ce/backend-melodic
      deploy: true
    secrets:
      registry_user: ${{ secrets.PORTUS_APP_USER }}
      registry_password: ${{ secrets.PORTUS_APP_TOKEN }}
