name: "CI - On PR"
on:
  pull_request:
    branches:
      - dev
      - main
      - "releases/**"
    paths-ignore:
      - ".bumpversion.cfg"
      - "setup.py"

jobs:
  CI-pip:
    uses: MOV-AI/.github/.github/workflows/py-workflow.yml@v1
    with:
      deploy: "false"
    secrets:
      auto_commit_user: ${{ secrets.RAISE_BOT_COMMIT_USER }}
      auto_commit_mail: ${{ secrets.RAISE_BOT_COMMIT_MAIL }}
      registry_user: ${{ secrets.PORTUS_APP_USER }}
      registry_password: ${{ secrets.PORTUS_APP_TOKEN }}
      nexus_publisher_user: ${{ secrets.NEXUS_PUBLISHER_USR }}
      nexus_publisher_password: ${{ secrets.NEXUS_PUBLISHER_PWD }}
      gh_token: ${{ secrets.GITHUB_TOKEN }}
      sonar_token: ${{ secrets.SONAR_TOKEN }}

  CI-version:
    needs: [CI-pip]
    runs-on: ubuntu-20.04
    outputs:
      version: ${{ steps.info.outputs.version }}
    steps:
      - name: Download a single artifact
        uses: actions/download-artifact@v2
        with:
          name: packages
          path: dist

      - name: Calc version
        id: info
        run: |
          package_name=$(find dist -type f -name *.whl)
          NEW_VERSIONING='[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+'
          version=$(echo $package_name | grep -Eo $NEW_VERSIONING )
          echo $version
          echo "::set-output name=version::$version"

  CI-docker-melodic:
    needs: [CI-version]
    uses: MOV-AI/.github/.github/workflows/docker-workflow.yml@feat/docker_args
    with:
      docker_file: docker/melodic/Dockerfile
      docker_image: devops/backend-melodic
      github_ref: ${{ github.ref }}
      build_args: PIP_PACKAGE_REPO=https://artifacts.cloud.mov.ai/repository/pypi-experimental/simple
      public: false
      public_image: ce/backend-melodic
      version: ${{ needs.CI-version.outputs.version }}
    secrets:
      registry_user: ${{ secrets.PORTUS_APP_USER }}
      registry_password: ${{ secrets.PORTUS_APP_TOKEN }}

  CI-docker-noetic:
    needs: [CI-version]
    uses: MOV-AI/.github/.github/workflows/docker-workflow.yml@feat/docker_args
    with:
      docker_file: docker/noetic/Dockerfile
      docker_image: devops/backend-noetic
      github_ref: ${{ github.ref }}
      build_args: PIP_PACKAGE_REPO=https://artifacts.cloud.mov.ai/repository/pypi-experimental/simple
      public: false
      public_image: ce/backend-noetic
      version: ${{ needs.CI-version.outputs.version }}
    secrets:
      registry_user: ${{ secrets.PORTUS_APP_USER }}
      registry_password: ${{ secrets.PORTUS_APP_TOKEN }}
